### ISSUE TITLE
List Index out of range

### ISSUE THREAD

**Issue by guptayuvraj** [ZacSweers/fb_group_analytics#1]
![abc](https://cloud.githubusercontent.com/assets/1355522/3549294/23571c9c-08c5-11e4-8061-ff46e5a6f256.png)

Please find the image.
This is the error I am facing.

Kindly help me resolve it asap.

**Comment by ZacSweers** [comment]
Do you have the latest version of the code? That doesn't appear to match how `run.py` currently looks
